version: "3"

networks:
  backend:

services:
  api:
    container_name: node
    build: .
    command: yarn run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    networks:
      - backend
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend